# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Benchmark

on:
  release:
    types:
      - created

jobs:
  benchmark:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        benchmark-script: [benchmark-512, benchmark-4096, benchmark-8192, benchmark-32768]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm run ${{ matrix.benchmark-script }}
